### PR TITLE
Annotate redundant functions

### PR DESCRIPTION
**Pull request by cthoyt**
# Summary
 
As a follow-up to #33, this PR adds a `duplicate_of` annotation to the `rexmex.utils.Annotator` class and begins annotating which functions are duplicate of each other.

~**Caveat** I'm not really happy with the direction of which is the "duplicate" in many cases, e.g., where `miss_rate` is the "canonical" one and "false_negative_rate" is the duplicate~

- [x] Code passes all tests
- [x] Unit tests provided for these changes
- [x] Documentation and docstrings added for these changes
- [x] Check all functions are annotated, and correctly

## Changes 

- Add new annotation `duplicate_of` to `rexmex.utils.Annotator`
- Annotate duplicate functions (e.g., `precision_score` is a duplicate of `positive_predictive_value`)
- Pins `pandas<=1.3.5` since they just put the 1.4 release candidate up on PyPI this morning and it doesn't work with the conda env in the GHA workflow

### CODE REVIEW

**Comment by cthoyt** [comment]
@benedekrozemberczki what do you think about changing the way the functions are annotated as redundant?

**Comment by benedekrozemberczki** [comment]
@cthoyt Feel free to switch around the naming and choose the standard function and annotate the others as you see fit.

**Comment by cthoyt** [comment]
@benedekrozemberczki sorry that the diff is a bit messy - I did some reorganizing of the order of the function definitions. I opted to use the most descriptive names (e.g., use true positive rate over sensitivity) as the defaults.

This PR also now introduces a helper function in the `Annotator` class to reduce the annotations in the duplicate functions by looking them up from the canonical one.

There's one bizarre quirk I noticed - the `recall_score` implementation from scikit-learn requires binarization while its counterparts in rexmex (true_positive_rate, etc.) do not.

This PR is ready for review.

**Comment by benedekrozemberczki** [comment]
Dear @cthoyt,

This looks amazing - thank you for all of the work. For now, we will release 0.1.0. and do a bit of promotion next week for this.

Bests,

Benedek

**Pull request merged**
